### ISSUE TITLE
Please add changve to course repo

### ISSUE THREAD

**Issue by changve** [bcb420-2023/Student-wiki#1]
Student name: Veronica Chang
GitHub Handle: changve

**Comment by risserlin** [comment]
created repo - [Veronica_Chang](https://github.com/bcb420-2023/Veronica_Chang) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
