### ISSUE TITLE
BCB-420 Request to be added to the organizations

### ISSUE THREAD

**Issue by metyu-melkonyan** [bcb420-2023/Student-wiki#10]
Hello,

Name: Metyu Melkonyan
githubusername:metyu-melkonyan

**Comment by risserlin** [comment]
created repo - [Metyu_Melkonyan](https://github.com/bcb420-2023/Metyu_Melkonyan) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
