### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by Kuan-Pang** [bcb420-2023/Student-wiki#15]
Student name: Kuan Pang
Github name: Kuan-Pang

**Comment by risserlin** [comment]
created repo - [Kuan_Pang](https://github.com/bcb420-2023/Kuan_Pang) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
