### ISSUE TITLE
Add @rayanalim to course repo

### ISSUE THREAD

**Issue by RayanAlim** [bcb420-2023/Student-wiki#2]
Student name: Rayan Awad Alim
GitHub username: rayanalim

**Comment by risserlin** [comment]
created repo - [Rayan_AwadAlim](https://github.com/bcb420-2023/Rayan_AwadAlim) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester.  If you have any issues please let me know.
