### ISSUE TITLE
request to be added to the BCB420 organization - hjovi1

### ISSUE THREAD

**Issue by hjovi1** [bcb420-2023/Student-wiki#20]
Student name: Helena Jovic
GitHub username: hjovi1

**Comment by risserlin** [comment]
missing student name.  Please add:
student name - ???
github username- hjovi1

**Comment by hjovi1** [comment]
Student name: Helena Jovic

**Comment by risserlin** [comment]
created repo - [Helena_Jovic](https://github.com/bcb420-2023/Helena_Jovic) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
