### ISSUE TITLE
Add benz0id to organization

### ISSUE THREAD

**Issue by benz0id** [bcb420-2023/Student-wiki#21]
could you please add benz0id to the organization.

**Comment by risserlin** [comment]
missing student name. Please add:
student name - ???
github username- benz0id

**Comment by benz0id** [comment]
Benjamin Tudor Price

**Comment by risserlin** [comment]
created repo - [BenjaminTudor_Price](https://github.com/bcb420-2023/BenjaminTudor_Price) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
