### ISSUE TITLE
Add tseamuscorlett to organization

### ISSUE THREAD

**Issue by tseamuscorlett** [bcb420-2023/Student-wiki#22]
tseamuscorlett

Hello!

**Comment by risserlin** [comment]
missing student name. Please add:
student name - ???
github username- tseamuscorlett

**Comment by tseamuscorlett** [comment]
student name - Tatsuya Corlett
github username- tseamuscorlett

**Comment by risserlin** [comment]
created repo - [Tatsuya_Corlett](https://github.com/bcb420-2023/Tatsuya_Corlett) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
