### ISSUE TITLE
zhouti34

### ISSUE THREAD

**Issue by zhouti34** [bcb420-2023/Student-wiki#23]

**Comment by zhouti34** [comment]
student name: tianyan zhou
GitHub name: zhouti34

**Comment by risserlin** [comment]
created repo - [Tianyan_Zhou](https://github.com/bcb420-2023/Tianyan_Zhou) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
