### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by wjdwogud24** [bcb420-2023/Student-wiki#26]
Name: Jae Hyung Jung
Github username: wjdwogud24

**Comment by risserlin** [comment]
created repo - [JaeHyung_Jung](https://github.com/bcb420-2023/JaeHyung_Jung) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
