### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by NithilanManimaran** [bcb420-2023/Student-wiki#28]
Name: Nithilan Manimaran
GitHub Username: NithilanManimaran

**Comment by risserlin** [comment]
created repo - [Nithilan_Manimaran](https://github.com/bcb420-2023/Nithilan_Manimaran) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.

**Comment by NithilanManimaran** [comment]
Hi, I don't think I am in the Students team. I am unable to add my wiki to the student wiki page since I don't have edit permissions. Not sure if this was the cause, but I was shortly removed from the course. Can I be re-added to the team?

**Comment by risserlin** [comment]
I sent you another invitation to the Student Team.
