### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by ghost** [bcb420-2023/Student-wiki#3]
Student name: Jun Hyuk Park
Github username: UVUO

**Comment by risserlin** [comment]
created repo - [JunHyuk_Park](https://github.com/bcb420-2023/JunHyuk_Park) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
