### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by re-mint** [bcb420-2023/Student-wiki#33]
Name. Babak Eric Jadidzadeh
Number. 998595541
GitHub username. re-mint

**Comment by risserlin** [comment]
created repo - [BabakEric_Jadidzadeh](https://github.com/bcb420-2023/BabakEric_Jadidzadeh) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
