### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by shaunavron** [bcb420-2023/Student-wiki#38]
GitHub username: shaunamia

**Comment by risserlin** [comment]
Student name: ????
GitHub username: shaunamia

Please add your student name

**Comment by shaunavron** [comment]
Student name: Shauna Vronces
GitHub username: shaunamia

**Comment by risserlin** [comment]
created repo - [Shauna_Vronces](https://github.com/bcb420-2023/Shauna_Vronces) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
