### ISSUE TITLE
Request to be added to student repo 

### ISSUE THREAD

**Issue by RicoZong** [bcb420-2023/Student-wiki#39]
Student name: Ruicong Zong 
Github: RicoZong

**Comment by risserlin** [comment]
created repo - [Ruicong_Zong](https://github.com/bcb420-2023/Ruicong_Zong) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
