### ISSUE TITLE
Request to be added to BCB420-2023 wiki

### ISSUE THREAD

**Issue by Yasamin-Nourijelyani** [bcb420-2023/Student-wiki#4]
Student Name: Yasamin Nouri Jelyani
Github username: Yasamin-Nourijelyani

**Comment by risserlin** [comment]
created repo - [Yasamin_NouriJelyani](https://github.com/bcb420-2023/Yasamin_NouriJelyani) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
