### ISSUE TITLE
Github Name: Yue_Zhou (Yue-Zhou0429)

### ISSUE THREAD

**Issue by Yue-Zhou0429** [bcb420-2023/Student-wiki#41]
Student name: Yue Zhou
Github: Yue-Zhou0429

**Comment by risserlin** [comment]
created repo - [Yue Zhou](https://github.com/bcb420-2023/Yue_Zhou) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
