### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by ari-beau** [bcb420-2023/Student-wiki#5]
Student name: Arianne Christina Beauregard
Github username: ari-beau

**Comment by risserlin** [comment]
created repo - [ArianneChristina_Beauregard](https://github.com/bcb420-2023/ArianneChristina_Beauregard) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
