### ISSUE TITLE
Request to be added to the bcb420 repo

### ISSUE THREAD

**Issue by ShahzadaShameelFarooq** [bcb420-2023/Student-wiki#6]
Student name: Shahzada Muhammad Shameel Farooq
Github username: ShahzadaShameelFarooq

**Comment by risserlin** [comment]
created repo - [ShahzadaMuhammad_ShameelFarooq](https://github.com/bcb420-2023/ShahzadaMuhammad_ShameelFarooq) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
