### ISSUE TITLE
request to be added to organization bcb420-2023

### ISSUE THREAD

**Issue by Maryam-hkiabi** [bcb420-2023/Student-wiki#7]
student name: Maryam Hasanzadehkiabi
my GitHub username is: Maryam-hkiabi

**Comment by risserlin** [comment]
created repo - [Maryam_Hasanzadehkiabi](https://github.com/bcb420-2023/Maryam_Hasanzadehkiabi) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
