### ISSUE TITLE
Request to be added to bcb420-2023 organization

### ISSUE THREAD

**Issue by Lola-W** [bcb420-2023/Student-wiki#8]
Student name: Jiaming Weng
Github username: Lola-W

**Comment by risserlin** [comment]
created repo - [Jiaming_Weng](https://github.com/bcb420-2023/Jiaming_Weng) in the [bcb420-2023](https://github.com/bcb420-2023) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2023/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
